---
DATADOG_API_KEY: "SPECIFY_KEY_HERE"

DATADOG_AGENT_VERSION: '1:5.10.1-1'
datadog_agent_version: "{{ DATADOG_AGENT_VERSION }}"

datadog_apt_key: "0x226AE980C7A7DA52"
datadog_debian_pkgs:
  - apparmor-utils
  - build-essential
  - curl
  - g++
  - gcc
  - ipython
  - pkg-config
  - rsyslog
