---

MONGO_VERSION_MAJOR_MINOR: "4.2"
  #MONGO_CLIENT_MONGODB_APT_KEY: "d68fa50fea312927"
  #MONGO_CLIENT_MONGODB_APT_KEYSERVER: "keyserver.ubuntu.com"
  #MONGO_CLIENT_MONGODB_REPO: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
MONGODB_REPO: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ MONGO_VERSION_MAJOR_MINOR }} multiverse"
MONGODB_REPO_BIONIC: "deb http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/{{ MONGO_VERSION_MAJOR_MINOR }} multiverse"
MONGO_CLIENT_VERSION: "4.2.14"

mongo_client_debian_pkgs:
  - "mongodb-org-shell={{ MONGO_CLIENT_VERSION }}"
  - "mongodb-org-tools={{ MONGO_CLIENT_VERSION }}"
