---
dependencies:
  - common
  - role: supervisor
    supervisor_spec:
      - service: edxapp
        migration_check_services: "lms,cms,workers"
        python: "{{ edxapp_venv_bin }}/python"
        code: "{{ code_dirs[service_variants_enabled[0]] | default(None) }}"
        env: "{{ edxapp_app_dir | default(None) }}/edxapp_env"
  - edxapp_common
  - nltk
  - role: edx_themes
    theme_users:
      - "{{ edxapp_user }}"
    when: EDXAPP_ENABLE_COMPREHENSIVE_THEMING
