- name: Deploy Enterprise Learner Portal Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'learner_portal_enterprise'
    LEARNER_PORTAL_ENTERPRISE_ENABLED: True
    LEARNER_PORTAL_ENTERPRISE_SANDBOX_BUILD: False
  roles:
    - role: mfe
      MFE_NAME: learner-portal-enterprise
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE