---

ORACLEJDK_VERSION: "11.0.13"
# what the archive unpacks to
oraclejdk_base: "jdk1.8.0_131"
oraclejdk_build: "b11"
oraclejdk_platform: "linux"
oraclejdk_arch: "x64"
oraclejdk_file: "jdk-{{ ORACLEJDK_VERSION }}_{{ oraclejdk_platform }}-{{ oraclejdk_arch }}_bin.tar.gz"

#oraclejdk_url: "http://download.oracle.com/otn-pub/java/jdk/{{ ORACLEJDK_VERSION }}-{{ oraclejdk_build }}/d54c1d3a095b4ff2b6607d096fa80163/{{ oraclejdk_file }}"
oraclejdk_url: "http://download.oracle.com/otn-pub/java/jdk/{{ ORACLEJDK_VERSION }}-{{ oraclejdk_build }}/bdde8881e2e3437baa70044f884d2d67/{{ oraclejdk_file }}"

oraclejdk_link: "/usr/lib/jvm/java-11-oracle"

oraclejdk_debian_pkgs:
  - curl
